In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../models/monkey.tri", delim_whitespace=True, comment='#', header=None, dtype=np.float32)

In [2]:
df.head()

0         1         2    3    4    5         6         7         8   \
0  0.329580  0.169321  0.521407  0.5  0.7  0.3  0.801141 -0.001190  0.598437   
1  0.341076  0.129833  0.500776  0.5  0.7  0.3  0.724021 -0.242134  0.645863   
2  0.348952  0.169038  0.498902  0.5  0.7  0.3  0.767632 -0.000702  0.640858   
3  0.323406  0.137715  0.522880  0.5  0.7  0.3  0.757775 -0.256294  0.600024   
4  0.318799  0.096801  0.505737  0.5  0.7  0.3  0.590136 -0.459914  0.663442   

         9         10  
0  0.891866  0.588564  
1  0.881611  0.575125  
2  0.896347  0.578250  
3  0.881001  0.586218  
4  0.866682  0.578023

In [3]:
df.tail()

0         1         2    3    4    5         6         7   \
11803 -0.433311 -0.050357 -0.205242  0.5  0.7  0.3 -0.132389 -0.877773   
11804 -0.435227 -0.071342 -0.118323  0.5  0.7  0.3 -0.221076 -0.975219   
11805 -0.490821 -0.062137 -0.185953  0.5  0.7  0.3  0.080691 -0.894742   
11806 -0.491746 -0.074751 -0.129370  0.5  0.7  0.3  0.046236 -0.975951   
11807 -0.556903 -0.079148 -0.139415  0.5  0.7  0.3 -0.063906 -0.972289   

             8         9         10  
11803 -0.460341  0.314477  0.581974  
11804 -0.003388  0.351451  0.612562  
11805 -0.439192  0.304817  0.610897  
11806  0.212928  0.333254  0.633532  
11807  0.224769  0.310643  0.654046

In [4]:
df.values

array([[ 0.32958 ,  0.169321,  0.521407, ...,  0.598437,  0.891866,
         0.588564],
       [ 0.341076,  0.129833,  0.500776, ...,  0.645863,  0.881611,
         0.575125],
       [ 0.348952,  0.169038,  0.498902, ...,  0.640858,  0.896347,
         0.57825 ],
       ...,
       [-0.490821, -0.062137, -0.185953, ..., -0.439192,  0.304817,
         0.610897],
       [-0.491746, -0.074751, -0.12937 , ...,  0.212928,  0.333254,
         0.633532],
       [-0.556903, -0.079148, -0.139415, ...,  0.224769,  0.310643,
         0.654046]], dtype=float32)

In [5]:
df.values.shape

(11808, 11)

In [6]:
df.values

array([[ 0.32958 ,  0.169321,  0.521407, ...,  0.598437,  0.891866,
         0.588564],
       [ 0.341076,  0.129833,  0.500776, ...,  0.645863,  0.881611,
         0.575125],
       [ 0.348952,  0.169038,  0.498902, ...,  0.640858,  0.896347,
         0.57825 ],
       ...,
       [-0.490821, -0.062137, -0.185953, ..., -0.439192,  0.304817,
         0.610897],
       [-0.491746, -0.074751, -0.12937 , ...,  0.212928,  0.333254,
         0.633532],
       [-0.556903, -0.079148, -0.139415, ...,  0.224769,  0.310643,
         0.654046]], dtype=float32)

In [7]:
type(df.values)

numpy.ndarray

In [8]:
df.values[0]

array([ 0.32958 ,  0.169321,  0.521407,  0.5     ,  0.7     ,  0.3     ,
        0.801141, -0.00119 ,  0.598437,  0.891866,  0.588564],
      dtype=float32)

In [9]:
len(df.values[0])

11

In [10]:
df.values[0].shape

(11,)

In [11]:
df.values[0].reshape(11, 1).shape

(11, 1)

In [12]:
df.values[0].reshape(-1, 1).shape

(11, 1)

In [13]:
df.values[0]

array([ 0.32958 ,  0.169321,  0.521407,  0.5     ,  0.7     ,  0.3     ,
        0.801141, -0.00119 ,  0.598437,  0.891866,  0.588564],
      dtype=float32)

In [14]:
df.values[0][0:3]

array([0.32958 , 0.169321, 0.521407], dtype=float32)

In [15]:
df.values[0, 0:3]

array([0.32958 , 0.169321, 0.521407], dtype=float32)

In [16]:
df.values[0, 3:6]

array([0.5, 0.7, 0.3], dtype=float32)

In [17]:
df.values[:, 0:3]

array([[ 0.32958 ,  0.169321,  0.521407],
       [ 0.341076,  0.129833,  0.500776],
       [ 0.348952,  0.169038,  0.498902],
       ...,
       [-0.490821, -0.062137, -0.185953],
       [-0.491746, -0.074751, -0.12937 ],
       [-0.556903, -0.079148, -0.139415]], dtype=float32)

In [18]:
df.values[:, 0:3].shape

(11808, 3)

In [19]:
np.sum(df.values[:, 0:3])

3078.5317

In [20]:
np.mean(df.values[:, 0:3])

0.086905256

In [21]:
np.mean(df.values[:, 0:3], axis=1)

array([ 0.34010267,  0.323895  ,  0.338964  , ..., -0.24630368,
       -0.23195569, -0.25848866], dtype=float32)

In [22]:
np.mean(df.values[:, 0:3], axis=0)

array([-2.6652482e-09,  4.2110518e-02,  2.1860522e-01], dtype=float32)